SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 700
SCREEN_DIMENSIONS = (SCREEN_WIDTH, SCREEN_HEIGHT)

PLAYTIME = 60
MAX_FRUIT = 4
SPEED = 20
SPAWN_RATE = 60
CATCH_DISTANCE = 80

DEBUG = True

WINDOW_TITLE = "Fruit Catching Game"
