SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
SCREEN_DIMENSIONS = (SCREEN_WIDTH, SCREEN_HEIGHT)

PLAYTIME = 10
MAX_FRUIT = 7
SPEED = 10
SPAWN_RATE = 30
CATCH_DISTANCE = 200

DEBUG = True

WINDOW_TITLE = "Fruit Catching Game"
